package model;
// Generated Mar 16, 2018 9:31:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Seat generated by hbm2java
 */
public class Seat  implements java.io.Serializable {


     private SeatId id;
     private Studio studio;
     private Set<Transaction> transactions = new HashSet<Transaction>(0);

    public Seat() {
    }

	
    public Seat(SeatId id, Studio studio) {
        this.id = id;
        this.studio = studio;
    }
    public Seat(SeatId id, Studio studio, Set<Transaction> transactions) {
       this.id = id;
       this.studio = studio;
       this.transactions = transactions;
    }
   
    public SeatId getId() {
        return this.id;
    }
    
    public void setId(SeatId id) {
        this.id = id;
    }
    public Studio getStudio() {
        return this.studio;
    }
    
    public void setStudio(Studio studio) {
        this.studio = studio;
    }
    public Set<Transaction> getTransactions() {
        return this.transactions;
    }
    
    public void setTransactions(Set<Transaction> transactions) {
        this.transactions = transactions;
    }




}


