package model;
// Generated Mar 17, 2018 8:17:21 PM by Hibernate Tools 4.3.1



/**
 * Ticket generated by hbm2java
 */
public class Ticket  implements java.io.Serializable {


     private TicketId id;
     private Transaction transaction;

    public Ticket() {
    }

    public Ticket(TicketId id, Transaction transaction) {
       this.id = id;
       this.transaction = transaction;
    }
   
    public TicketId getId() {
        return this.id;
    }
    
    public void setId(TicketId id) {
        this.id = id;
    }
    public Transaction getTransaction() {
        return this.transaction;
    }
    
    public void setTransaction(Transaction transaction) {
        this.transaction = transaction;
    }




}


